name: openfoam
channels:
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - python==3.9.21
  - matplotlib
  - numpy
  - scipy
  - pip:
      - jinja2==3.1.5
      - markupsafe==3.0.2
      - openfoamparser==0.13
      - orr-sommerfeld==0.0.8
      - pyfoam==2023.7
